image: hirokimatsumoto/alpine-openjdk-11

variables:
  GIT_SUBMODULE_STRATEGY: recursive


stages:
  - build
  - test
  - coverage
  - install
  - run

before_script:
  - java -version
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - apk update && apk upgrade && apk add --no-cache git

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew check -i

coverage:
  stage: coverage
  script:
    - ./gradlew codeCoverageReport
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/",instructions, "instructions covered"; print 100*covered/instructions, "%covered" }' build/reports/jacoco/codeCoverageReport/codeCoverageReport.csv

install:
  stage: install
  script:
    - ./gradlew install
    - ./gradlew bundle
    - ./gradlew api

run:
  stage: run
  script:
    - ./gradlew run

after_script:
  - echo "End CI"
